### ISSUE TITLE
Add example of multiple commands (yarn install, yarn test)

### ISSUE THREAD

**Issue by mikeporterdev** [Borales/actions-yarn#11]
GItHub Actions is still relatively new and people are frequently still learning the syntax, myself included. It would be helpful if the README contained an example of a simple yarn install, yarn test workflow to demonstrate how it should be used with multiple commands.

**Comment by Borales** [comment]
@mikeporterdev Hi. I updated the main README file to show how to use yarn commands within a single build.

The main problem with having "multiple commands" defined for a single step is that if one of them fails - the whole step will fail, thus it will make it harder to investigate what exact command caused the problem. For this reason - I'm keeping a single command per step.

Please check README and let me know if it helps.

**Comment by mikeporterdev** [comment]
What you've added is great, just something that's helpful for people picking up the new tech 👍
