### ISSUE TITLE
Option to set working directory

### ISSUE THREAD

**Issue by JoshuaTruscott** [Borales/actions-yarn#12]
In my case, my yarn project is within a subdirectory, can you provide an option to set the working directory to be something other than the root directory of the repository? Or is this already possible and I'm missing something? Thanks!

**Comment by vpontis** [comment]
You can do `--cwd install`

**Comment by gagan0723** [comment]
@vpontis I think what @JoshuaTruscott mean is running commands on sub-directories, like `yarn lint`.

I am having the same issue where I have individual directories for `client` and `server` and both have their own linting rules.

Something on like this:
```bash
- uses: borales/actions-yarn@v2.0.0
  with:
   cmd: install # will run `yarn install` command
- uses: borales/actions-yarn@v2.0.0
  paths: |
        ./client
        ./server
  with:
    cmd: build # will run `yarn build` command
- uses: borales/actions-yarn@v2.0.0
  paths: |
        ./client
        ./server
  with:
    cmd: test # will run `yarn test` command
```

**Comment by relferreira** [comment]
@gagan0723 I think that @vpontis is saying to try something like this:

```
- name: Yarn install
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: --cwd ui install
```
