### ISSUE TITLE
Fails on node version

### ISSUE THREAD

**Issue by hennessyevan** [Borales/actions-yarn#16]
The engine "node" is incompatible with this module. Expected version "^12.1.0". Got "10.16.3"

**Comment by Borales** [comment]
@hennessyevan expected where?

**Comment by hennessyevan** [comment]
Sorry for not providing any details. 🙈 I have in `package.json`
```json
"engines": {
  "node": "^12"
}
```

Since this action runs from node:10.16-alpine that engine check fails for me. Node 12 is LTS now but is there anyway to specify the node version like the way that https://github.com/actions/setup-node does?

**Comment by Borales** [comment]
I updated the docker image to use node LTS version, please check it

**Comment by hennessyevan** [comment]
Perfect! Thanks 😄
