### ISSUE TITLE
Yarn version?

### ISSUE THREAD

**Issue by stoplion** [Borales/actions-yarn#25]
Is there a way to install a specific yarn version? 

getting the following error:
`error @: The engine "yarn" is incompatible with this module. Expected version "~1.21.0". Got "1.17.3"`

**Comment by emjimadhu** [comment]
I am looking for this too.

**Comment by Borales** [comment]
```
/usr/local/bin/yarnpkg -> /usr/local/lib/node_modules/yarn/bin/yarn.js
/usr/local/bin/yarn -> /usr/local/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.22.4
```

Yarn updated to the latest version

**Comment by Borales** [comment]
in v2.3.0 of this Github Action
