### ISSUE TITLE
Run action using Node 20

### ISSUE THREAD

**Issue by albireox** [Borales/actions-yarn#267]
GitHub is transitioning all actions to Node 20: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Currently `actions-yarn` emits a warning when used, since it still runs on Node 16.

**Comment by Borales** [comment]
@albireox that's a good one, I'll fix it

**Comment by Borales** [comment]
https://github.com/Borales/actions-yarn/releases/tag/v5.0.0
