### ISSUE TITLE
Cache installed packages if yarn.lock hasn't changed

### ISSUE THREAD

**Issue by robd003** [Borales/actions-yarn#276]
It would be great to have cache support so that if the hash for yarn.lock is the same instead of doing a full install during each run it would just load from cache

**Comment by Borales** [comment]
@robd003 you could still do that with https://github.com/actions/cache and conditionally calling `yarn install` if you had a "cache hit" (meaning "the cache was found for your yarn.lock checksum") - you could find more info in that repo.
