### ISSUE TITLE
Exit code of yarn task

### ISSUE THREAD

**Issue by tiarebalbi** [Borales/actions-yarn#3]
Hi there,

I'm using this action on one of my repo and I noticed that once I'm running the `yarn test` on my project the test step is getting blocked for like an hour but the step is taking only 3 minutes. Would this be related to the exit code of the task that is not being considered? 

Demo:
* https://github.com/tiarebalbi/tiarebalbi-website/runs/81658764

**Comment by JReinhold** [comment]
Judging by the demo, it looks like you are running the test in watch mode, hence it will never stop running.

When you are using Create React App (as you are), it will always run in watch-mode, unless the environment variable `CI` is set to `true` as documented [here](https://facebook.github.io/create-react-app/docs/running-tests#on-ci-servers). So I suggest you try setting the environment variable either [directly on the GitHub Action](https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/#environment-variables), or create a script in `package.json` that does it for you, eg:

```js
// package.json
...
"scripts": {
  ...
  "test:once": "cross-env CI=true test",
},
"devDependencies": {
  ...
  "cross-env": "*"
}
```

**Comment by tiarebalbi** [comment]
Yes this fixed the problem. Good to be closed.
