### ISSUE TITLE
ACTION-YARN

### ISSUE THREAD

**Issue by syedabbasrazashahzaidi** [Borales/actions-yarn#32]
error Couldn't find a package.json file in "/github/workspace"
HOW COULD I RESOLVE THIS ERROR? PLEASE TELL ME.

 - name: GitHub Action for Yarn
        uses: borales/actions-yarn@v2.0.0 # `yarn install`
        with:
          cmd: Install
      - name: Build React App
        run: yarn build              
IT GIVES THE SAME ERROR FOR ACTION-YARN@V2.1.0

**Comment by cvandradg** [comment]
u solved it?

**Comment by Borales** [comment]
Please check the latest release
