### ISSUE TITLE
Broken 404 link to repo github.com/actions/npm in README

### ISSUE THREAD

**Issue by generalmimon** [Borales/actions-yarn#33]
The beginning of the README on `master` currently looks like this:

https://github.com/Borales/actions-yarn/blob/3eab1c9435168a0cbc73878255be58bca3df6c43/README.md#L1-L4

However, access to https://github.com/actions/npm fails with the error "404 Page not found".

**Comment by Borales** [comment]
https://github.com/actions/setup-node
