### ISSUE TITLE
Error when deleting build directory

### ISSUE THREAD

**Issue by rohmanitsavirus** [Borales/actions-yarn#39]
I got an error when re-running the workflow.
```
Deleting the contents of '/home/.../action-runner/app/.../...'
Error: Command failed: rm -rf '/home/.../action-runner/app/.../.../build'
```
that error appears because the build directory is owned by root
![image](https://user-images.githubusercontent.com/70248026/127950389-e9d9387c-780c-400e-b42c-30ba5e4d0c84.png)

There are 2 achievements to remove this error.
1. Install and build without [sudo](#37 )
2. Remove command using `sudo`

Right now I can disable the error using `chmod` but it's a temporary solution

**Comment by NapoSky** [comment]
Bump, definitely need it.

**Comment by Borales** [comment]
Please check the latest release
