### ISSUE TITLE
ERROR: unable to select packages

### ISSUE THREAD

**Issue by star123good** [Borales/actions-yarn#46]
Build container for action use: '/home/runner/work/_actions/Borales/actions-yarn/v2.3.0/Dockerfile'.
  /usr/bin/docker build -t 6f1554:b36085a[2](https://github.com/Tydeihealth/tydei-dev/runs/6788415132?check_suite_focus=true#step:2:2)4d0d42b083a03ece37d7c9aa -f "/home/runner/work/_actions/Borales/actions-yarn/v2.3.0/Dockerfile" "/home/runner/work/_actions/Borales/actions-yarn/v2.3.0"
  Sending build context to Docker daemon  7.168kB
  
  Step 1/6 : FROM node:lts-alpine
  lts-alpine: Pulling from library/node
  2408cc74d12b: Pulling fs layer
  5b80453a567d: Pulling fs layer
  3420de6432e1: Pulling fs layer
  65b549a28248: Pulling fs layer
  65b549a28248: Waiting
  3420de6432e1: Verifying Checksum
  3420de6432e1: Download complete
  2408cc74d12b: Verifying Checksum
  2408cc74d12b: Download complete
  65b549a28248: Verifying Checksum
  65b549a28248: Download complete
  2408cc74d12b: Pull complete
  5b80453a567d: Verifying Checksum
  5b80453a567d: Download complete
  5b80453a567d: Pull complete
  3420de6432e1: Pull complete
  65b549a28248: Pull complete
  Digest: sha256:c785e617c8d7015190c0d41af52cc69be8a16e3d9eb7cb21f0bb58bcfca14d6b
  Status: Downloaded newer image for node:lts-alpine
   ---> 97c7a05048e1
  Step 2/6 : RUN apk add --no-cache git python2 build-base
   ---> Running in 363945bd57ca
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
  ERROR: unable to select packages:
    python2 (no such package):
      required by: world[python2]
  The command '/bin/sh -c apk add --no-cache git python2 build-base' returned a non-zero code: 1
  Warning: Docker build failed with exit code 1, back off 7.955 seconds before retry.
  /usr/bin/docker build -t 6f1554:b36085a24d0d42b083a03ece37d7c9aa -f "/home/runner/work/_actions/Borales/actions-yarn/v2.3.0/Dockerfile" "/home/runner/work/_actions/Borales/actions-yarn/v2.3.0"
  Sending build context to Docker daemon  7.168kB
  
  Step 1/6 : FROM node:lts-alpine
   ---> 97c7a05048e1
  Step 2/6 : RUN apk add --no-cache git python2 build-base
   ---> Running in b1ba2ebc4[3](https://github.com/Tydeihealth/tydei-dev/runs/6788415132?check_suite_focus=true#step:2:3)a1
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
  ERROR: unable to select packages:
    python2 (no such package):
      required by: world[python2]
  The command '/bin/sh -c apk add --no-cache git python2 build-base' returned a non-zero code: 1
  Warning: Docker build failed with exit code 1, back off 1.736 seconds before retry.
  /usr/bin/docker build -t 6f1554:b36085a24d0d42b083a03ece37d7c9aa -f "/home/runner/work/_actions/Borales/actions-yarn/v2.3.0/Dockerfile" "/home/runner/work/_actions/Borales/actions-yarn/v2.3.0"
  Sending build context to Docker daemon  7.168kB
  
  Step 1/6 : FROM node:lts-alpine
   ---> 97c7a050[4](https://github.com/Tydeihealth/tydei-dev/runs/6788415132?check_suite_focus=true#step:2:4)8e1
  Step 2/6 : RUN apk add --no-cache git python2 build-base
   ---> Running in 4e1db9[5](https://github.com/Tydeihealth/tydei-dev/runs/6788415132?check_suite_focus=true#step:2:5)e5e8b
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.1[6](https://github.com/Tydeihealth/tydei-dev/runs/6788415132?check_suite_focus=true#step:2:6)/main/x[8](https://github.com/Tydeihealth/tydei-dev/runs/6788415132?check_suite_focus=true#step:2:8)6_64/APKINDEX.tar.gz
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.[16](https://github.com/Tydeihealth/tydei-dev/runs/6788415132?check_suite_focus=true#step:2:16)/community/x86_64/APKINDEX.tar.gz
  ERROR: unable to select packages:
    python2 (no such package):
      required by: world[python2]
  The command '/bin/sh -c apk add --no-cache git python2 build-base' returned a non-zero code: 1
Error: Docker build failed with exit code 1

**Comment by Borales** [comment]
@star123good it was fixed a few minutes ago, please check https://github.com/Borales/actions-yarn/releases/tag/v3.0.0

**Comment by star123good** [comment]
Thank you, @Borales
