### ISSUE TITLE
Could you release major version(s) of your GitHub action?

### ISSUE THREAD

**Issue by jmfayard** [Borales/actions-yarn#50]
Bonjour! 🇫🇷

I contribute to [GitHub Actions Kotlin DSL](https://github.com/krzema12/github-actions-kotlin-dsl) which provides an alternative to write GitHub Actions not in YAML but in a type-safe programming language: Kotlin.

To this end we provide type-safe wrappers for currently [72 (and counting) wrapper actions](https://krzema12.github.io/github-actions-kotlin-dsl/supported-actions/). Those type-safe wrappers are generated from its `action.yml` which we update when it goes to a new major version, for example `actions/cache@v2` to `actions/cache@v3`

And of course we support your action as well!

Unfortunately when an action don't have a major version, which is what GitHub recommands, we are forced to update manually for every minor version, like from `appleboy/scp-action/v0.1.2` to `appleboy/scp-action/v0.1.3` 

See [our issue here](https://github.com/krzema12/github-actions-kotlin-dsl/issues/289)

Would you consider creating a major version for your action?
That would make our life easier, and the life of your users easier in general.

You can find here the recommendations from GitHub:

[https://github.com/actions/toolkit/blob/main/docs/action-versioning.md](https://github.com/actions/toolkit/blob/main/docs/action-versioning.md) 
(see *Recommendations* in particular)

**Comment by jmfayard** [comment]
@Borales 
what I mean is that if you create a release `v3`
then people can use in their workflow `borales/actions-yarn@v3` and get all the minor updates.
That doesn't work with only a release `v3.0.0`
See https://github.com/actions/toolkit/blob/main/docs/action-versioning.md

**Comment by jmfayard** [comment]
Actually from what I understand from https://github.com/actions/toolkit/blob/main/docs/action-versioning.md#recommendations it's not a release, it's simply a tag `v3` that you update when you do a new release

```
git tag -fa v3 -m "Update v3 tag"
git push origin v3 --force
```

**Comment by Borales** [comment]
@jmfayard pushed

**Comment by jmfayard** [comment]
Thanks a lot :)
