### ISSUE TITLE
actions-yarn will remove git history from actions/checkout

### ISSUE THREAD

**Issue by ykla** [Borales/actions-yarn#51]
The vuepress using git history as a generating part of the data for the lastUpdatedText component. I've been having trouble generating normal pages with actions-yarn. I tried for 16 hours to fix this strange problem. Eventually I compiled locally and found everything worked, and I'm now using the deployment scheme provided by [vuepress' default tutorial](https://v2.vuepress.vuejs.org/guide/deployment.html).

https://github.com/FreeBSD-Ask/Handbook-Next/actions/runs/2564569713

https://github.com/FreeBSD-Ask/Handbook-Next/runs/7062399172?check_suite_focus=true

actions/checkout sets fetch-depth: 0 to save git history. Hopefully actions-yarn will have this parameter as well. Thanks  a lot.

**Comment by Borales** [comment]
Please check the latest release
