### ISSUE TITLE
Cannot install specific module using `yarn add`

### ISSUE THREAD

**Issue by jc-greenhouse** [Borales/actions-yarn#62]
I would like to use this github action in order to install a specific public package. Attempting to use `yarn add`, however, results in an error (shown below). Is yarn add not supported at this time?

In the docs, I mostly see one work arguments being used, such as `install` and `test`.
  
Version: `borales/actions-yarn@v4`

Environment: [act](https://github.com/nektos/act) github actions simulator 

Error:

```
| [command]/usr/local/bin/yarn add widdershins
| yarn run v1.22.10
| error Command "add widdershins" not found.
| info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[Update Harvest Documentation/build]   ❗  ::error::The process '/usr/local/bin/yarn' failed with exit code 1
[Update Harvest Documentation/build]   ❌  Failure - Main Install yarn and widdershins
[Update Harvest Documentation/build]   ⚙  ::set-output:: yarn-version=1.22.10
[Update Harvest Documentation/build] exitcode '1': failure
[Update Harvest Documentation/build] 🏁  Job failed
Error: Job 'build' failed
```

Relevant configuration: 

```
   - name: Install yarn and widdershins
        uses: borales/actions-yarn@v4
        with:
          cmd: add widdershins
```

**Comment by Borales** [comment]
@jc-greenhouse try now. I've pushed the fix, it's on `v4` now.
