### ISSUE TITLE
Publish to dockerhub

### ISSUE THREAD

**Issue by ardeois** [Borales/actions-yarn#8]
Hi there and thanks for this github action, it's very useful !

It would be even better if you would publish this action to docker hub.

In the workflow.yml file, instead of doing:
```yaml
- uses: Borales/actions-yarn@master
```

We could do
```yaml
- uses: docker://Borales/actions-yarn@latest
```

This would fasten actions process time, as it would only pull the image instead of building it.

Any thoughts?

**Comment by Borales** [comment]
@ardeois @jpvalery sure, I'm gonna do that (but first I'd need to update github actions for this repo - it should be publishing the image to Docker Hub, but it seems to be broken).

**Comment by Borales** [comment]
@ardeois @jpvalery pushed the latest to https://hub.docker.com/r/borales/yarn/tags

- now uses `node:10.16-alpine` (25MB vs 51MB previously)
- it also can be used as "repo as an action" (`borales/actions-yarn@master`) or prebuilt Docker image

**Comment by ardeois** [comment]
Great thanks @Borales we'll test that !
